# tasks/main.yml
---
- name: Installing ufw
  apt:
    pkg: "ufw"
    state: present
    update_cache: "yes"

- name: Configuring firewall
  template:
    src: ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: reload ufw

- name: Resetting firewall
  ufw:
    state: reset
  changed_when: false
  when: ufw_strict

- name: Configuring port/protocol/network rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  changed_when: "not ufw_strict"

- name: Configuring application rules
  ufw:
    name: "{{ item.name }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
  with_items: "{{ ufw_applications }}"
  changed_when: false

- name: Configuring service
  ufw:
    state: "{{ ufw_state }}"
    logging: "{{ ufw_logging }}"
  changed_when: false

- name: Enabling service
  service:
    name: ufw
    state: "{{ ufw_service_state }}"
    enabled: "{{ ufw_service_enabled }}"
