---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: 'yes'
        cache_valid_time: '600'
      when: ansible_distribution == 'Ubuntu'

  vars:
    ufw_state: enabled
    ufw_ipv6: "no"
    ufw_default_forward_policy: ACCEPT
    ufw_logging: low
    ufw_strict: true
    ufw_rules:
      - { port: 22, rule: allow, comment: "OpenSSH" }
      - { port: 80, rule: allow, comment: "http" }
      - { port: 443, rule: allow, comment: "https" }
    ufw_applications: []
